name: CD Pipe

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'                # set this to the .NET Core version to use
  WEBAPP: app-rebu-api03-dev
  GROUP: rg-rebu-dev
  ACCOUNT: blobgithubdeploydev  # Does not have to exist, this will be created for you
  CONTAINER: apicore-deploy
  EXPIRY_TIME: 20 minutes
  APP_URL: https://app-rebu-api03-dev.azurewebsites.net

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  poc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: dotnet publish
      run: dotnet publish ./WebApplication1 -c Release --property:PublishDir=../myapp

    - name: List Files
      run: ls -R ./myapp/

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB }}
        
    - name: Zip the app contents
      uses: vimtor/action-zip@v1.2
      with:
        files: ./myapp/
        recursive: true
        dest: app.zip

    - name: Set SAS token expiration
      run: echo "expiry=`date -u -d "$EXPIRY_TIME" '+%Y-%m-%dT%H:%MZ'`" >> $GITHUB_ENV
      
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az extension add --name webapp
          az storage container create -n $CONTAINER --account-name $ACCOUNT
          az storage blob upload -f app.zip --overwrite --account-name $ACCOUNT -c $CONTAINER -n $ACCOUNT
          ZIP_URL=$(az storage blob generate-sas --full-uri --permissions r --expiry ${{ env.expiry }} --account-name $ACCOUNT -c $CONTAINER -n $ACCOUNT | xargs)
          az webapp deploy --name $WEBAPP --resource-group $GROUP --type zip --src-url  $ZIP_URL --async false
